//
//  PhotosCollectionRouter.swift
//  STPhotoCollection-iOS
//
//  Created by Dimitri Strauneanu on 08/08/2017.
//  Copyright (c) 2017 Streetography. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import STPhotoCore

protocol PhotosCollectionRoutingLogic: NSObjectProtocol {
    func removeViewController()
    func presentPhotoDetailView(photo: STPhoto)
}

protocol PhotosCollectionDataPassing {
    var dataStore: PhotosCollectionDataStore? { get }
}

class PhotosCollectionRouter: NSObject, PhotosCollectionRoutingLogic, PhotosCollectionDataPassing {
    weak var viewController: PhotosCollectionViewController?
    var dataStore: PhotosCollectionDataStore?
    
    func removeViewController() {
        if let navigationController = self.viewController?.navigationController {
            navigationController.popViewController(animated: true)
        } else {
            self.viewController?.dismiss(animated: true, completion: nil)
        }
    }
    
    func presentPhotoDetailView(photo: STPhoto) {
        DispatchQueue.main.async {
//            let photoDetailsViewController = PhotoDetailsViewController(photoId: photo.id)
//            photoDetailsViewController.hidesBottomBarWhenPushed = true
//            photoDetailsViewController.delegate = self.viewController
//            self.viewController?.navigationController?.pushViewController(photoDetailsViewController, animated: true)
        }
    }
}
