//
//  STPhotoCollectionRouter.swift
//  STPhotoCollection-iOS
//
//  Created by Dimitri Strauneanu on 08/08/2017.
//  Copyright (c) 2017 Streetography. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import STPhotoCore

protocol STPhotoCollectionRoutingLogic: NSObjectProtocol {
    func removeViewController()
}

protocol STPhotoCollectionDataPassing {
    var dataStore: STPhotoCollectionDataStore? { get }
}

class STPhotoCollectionRouter: NSObject, STPhotoCollectionRoutingLogic, STPhotoCollectionDataPassing {
    weak var viewController: STPhotoCollectionViewController?
    var dataStore: STPhotoCollectionDataStore?
    
    func removeViewController() {
        if self.viewController?.navigationController?.viewControllers.first == viewController {
            self.viewController?.dismiss(animated: true, completion: nil)
        } else if let navigationController = self.viewController?.navigationController {
            navigationController.popViewController(animated: true)
        } else {
            self.viewController?.dismiss(animated: true, completion: nil)
        }
    }
}
