//
//  STPhotoCollectionPresenter.swift
//  STPhotoCollection-iOS
//
//  Created by Dimitri Strauneanu on 08/08/2017.
//  Copyright (c) 2017 Streetography. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import STPhotoCore

protocol STPhotoCollectionPresentationLogic {
    func presentFetchedPhotos(response: STPhotoCollection.FetchPhotos.Response)
    func presentEntityDetails(response: STPhotoCollection.PresentEntityDetails.Response)
    
    func presentWillFetchEntityDetails()
    func presentDidFetchEntityDetails()
    
    func presentWillFetchPhotos()
    func presentDidFetchPhotos()
    
    func presentNoPhotos()
    func presentNoMorePhotos()
    
    func presentPhotoDetailView(response: STPhotoCollection.PresentPhotoDetail.Response)
    
    func presentWillFetchImage(response: STPhotoCollection.FetchImage.Response)
    func presentDidFetchImage(response: STPhotoCollection.FetchImage.Response)
    func presentImage(response: STPhotoCollection.FetchImage.Response)
}

class STPhotoCollectionPresenter: STPhotoCollectionPresentationLogic {
    weak var displayer: STPhotoCollectionDisplayLogic?
    
    func presentEntityDetails(response: STPhotoCollection.PresentEntityDetails.Response) {
        let title: String? = response.name
        let imageName: String? = self.imageNameForEntityLevel(level: response.level)
        let viewModel = STPhotoCollection.PresentEntityDetails.ViewModel(title: title, imageName: imageName)
        self.displayer?.displayEntityDetails(viewModel: viewModel)
    }
    
    private func imageNameForEntityLevel(level: EntityLevel?) -> String? {
        guard let level = level else { return nil }
        switch level {
            case .location: return nil
            case .block: return "st_photo_collection_block"
            case .neighborhood: return "st_photo_collection_neighborhood"
            case .city: return "st_photo_collection_city"
            case .county: return "st_photo_collection_county"
            case .state: return "st_photo_collection_state_region"
            case .country: return "st_photo_collection_country"
            case .unknown: return nil
        }
    }
    
    func presentFetchedPhotos(response: STPhotoCollection.FetchPhotos.Response) {
        let displayedPhotos = self.displayedPhotosFor(photos: response.photos, size: response.photoSize)
        let viewModel = STPhotoCollection.FetchPhotos.ViewModel(displayedPhotos: displayedPhotos)
        self.displayer?.displayFetchedPhotos(viewModel: viewModel)
    }
    
    private func displayedPhotosFor(photos: [STPhoto], size: CGSize) -> [STPhotoCollection.DisplayedPhoto] {
        var displayedPhotos: [STPhotoCollection.DisplayedPhoto] = []
        for i in 0..<photos.count {
            var itemSize = size
            if i == 0 {
                itemSize.width *= 2
                itemSize.height *= 2
            }
            displayedPhotos.append(self.displayedPhotoFor(photo: photos[i], size: itemSize))
        }
        return displayedPhotos
    }
    
    private func displayedPhotoFor(photo: STPhoto, size: CGSize) -> STPhotoCollection.DisplayedPhoto {
        let imageUrl: String? = photo.imageUrl
        let backgroundImageColor = UIColor(hexString: photo.dominantColor)
        let displayedPhoto = STPhotoCollection.DisplayedPhoto(id: photo.id)
        displayedPhoto.imageUrl = imageUrl
        displayedPhoto.backgroundImageColor = backgroundImageColor
        return displayedPhoto
    }
    
    func presentWillFetchEntityDetails() {
        self.displayer?.displayWillFetchEntityDetails()
    }
    
    func presentDidFetchEntityDetails() {
        self.displayer?.displayDidFetchEntityDetails()
    }
    
    func presentWillFetchPhotos() {
        self.displayer?.displayWillFetchPhotos()
    }
    
    func presentDidFetchPhotos() {
        self.displayer?.displayDidFetchPhotos()
    }
    
    func presentNoPhotos() {
        self.displayer?.displayNoPhotos()
    }
    
    func presentNoMorePhotos() {
        self.displayer?.displayNoMorePhotos()
    }
    
    func presentPhotoDetailView(response: STPhotoCollection.PresentPhotoDetail.Response) {
        let viewModel = STPhotoCollection.PresentPhotoDetail.ViewModel(photoId: response.photoId)
        self.displayer?.displayPhotoDetailView(viewModel: viewModel)
    }
    
    // MARK: Fetch image
    
    func presentWillFetchImage(response: STPhotoCollection.FetchImage.Response) {
        self.displayer?.displayWillFetchImage(viewModel: STPhotoCollection.FetchImage.ViewModel(displayedPhoto: response.displayedPhoto, image: response.image))
    }
    
    func presentDidFetchImage(response: STPhotoCollection.FetchImage.Response) {
        self.displayer?.displayDidFetchImage(viewModel: STPhotoCollection.FetchImage.ViewModel(displayedPhoto: response.displayedPhoto, image: response.image))
    }
    
    func presentImage(response: STPhotoCollection.FetchImage.Response) {
        self.displayer?.displayImage(viewModel: STPhotoCollection.FetchImage.ViewModel(displayedPhoto: response.displayedPhoto, image: response.image))
    }
}
